### PR TITLE
Fixing the cloudbuild so it properly runs

### PR DESCRIPTION
**Pull request by Faffnir**
Signed-off-by: Faffnir <david.leib@camunda.com>

### CODE REVIEW

**Review by afirth — APPROVED** [review]
Oh clean. This is a fork of upstream so please push up there

**Comment by Faffnir** [comment]
> Oh clean. This is a fork of upstream so please push up there

We are actually ahead of the remote branch by 3 commits already... Can I just merge it because I need it for monitoring. I promise to follow up on pushing this upstream afterwards...

**Comment by afirth** [comment]
upstream: https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/455

**Comment by afirth** [comment]
@Faffnir you need to sign the google CLA at https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/455

**Pull request merged**
